# This is the configuration file that is used by `cargo-about` to check license compatibility.

accepted = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]

# For now, we include these so that the number of gathered crates matches the number of crates in `Cargo.lock`.
ignore-build-dependencies = false
ignore-dev-dependencies = false
